services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    privileged: true  # Nécessaire pour Kind et Docker
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # Configuration Jenkins existante
      - ./jenkins_home:/var/jenkins_home:z
      # Socket Docker pour Kind (Kind utilise Docker, pas Podman)
      - /var/run/docker.sock:/var/run/docker.sock:z
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
      - DOCKER_HOST=unix:///var/run/docker.sock
    user: "0"  # Root pour accès Docker socket
